apiVersion: velacp.oam.dev/v1alpha1
kind: AppTemplate
metadata:
  name: app-template-1
spec:
  template:
    components:
      - name: backend
        type: worker
        settings:
          cmd:
            - sleep
            - '1000'
      - name: frontend
        type: webservice
        settings:
          image: nginx
        traits:
          - name: autoscaler
            properties:
              min: 1
              max: 10
  patch:
    - envs:
        - env-1
      components:
        - name: backend
          type: "" # TODO: oamcore types require this. Make this optional
          settings:
            image: busybox
        - name: frontend
          type: "" # TODO: oamcore types require this. Make this optional
          settings: {} # TODO: oamcore types require this. Make this optional
          traits:
            - name: sidecar
              properties:
                image: "fluentd"