apiVersion: velacp.oam.dev/v1alpha1
kind: Application
metadata:
  name: app-1
spec:
  env: env-1
  components:
    - name: backend
      type: worker
      settings:
        cmd:
          - sleep
          - '1000'
    - name: frontend
      type: webservice
      settings:
        image: nginx
      traits:
        - name: autoscaler
          properties:
            min: 1
            max: 10
        - name: sidecar
          properties:
            name: "sidecar-test"