# permissions for end users to edit apptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apptemplate-editor-role
rules:
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - apptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - apptemplates/status
  verbs:
  - get
