# permissions for end users to view apptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apptemplate-viewer-role
rules:
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - apptemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - apptemplates/status
  verbs:
  - get
