# permissions for end users to edit catalogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalog-editor-role
rules:
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - catalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - catalogs/status
  verbs:
  - get
