# permissions for end users to view catalogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalog-viewer-role
rules:
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - catalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - catalogs/status
  verbs:
  - get
