
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - catalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - catalogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - environments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - environments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - packages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velacp.oam.dev.velacp.oam.dev
  resources:
  - packages/status
  verbs:
  - get
  - patch
  - update
